-- ============================================================================
-- Script: 01_create_balance_sheet_table.sql
-- Purpose: Create the ACTUAL_AA_BALANCE_SHEET table with financial columns
-- ============================================================================
USE ROLE SYSADMIN;

-- Create database and schema if not exists
CREATE DATABASE IF NOT EXISTS FINANCE_DB;
CREATE SCHEMA IF NOT EXISTS FINANCE_DB.BALANCE_SHEET;

USE DATABASE FINANCE_DB;
USE SCHEMA FINANCE_DB.BALANCE_SHEET;

-- Create the main balance sheet table
CREATE OR REPLACE TABLE ACTUAL_AA_BALANCE_SHEET (
    -- Primary Key (auto-generated)
    RECORD_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    
    -- Business Grouping Key Columns (8 columns)
    PORTFOLIO_TICKER VARCHAR(50) NOT NULL,
    REPORTING_FREQUENCY VARCHAR(20) NOT NULL,          -- DAILY, WEEKLY, MONTHLY, QUARTERLY, ANNUAL
    REPORTING_CURRENCY VARCHAR(10) NOT NULL,           -- USD, EUR, GBP, etc.
    VALUE_DATE DATE NOT NULL,
    PRELIMINARY BOOLEAN NOT NULL DEFAULT FALSE,        -- TRUE if preliminary, FALSE if final
    SOURCE VARCHAR(100) NOT NULL,                      -- Data source system
    ACCT_BASIS VARCHAR(20) NOT NULL,                   -- GAAP, IFRS, STAT, etc.
    BALANCE_SHEET_TYPE VARCHAR(50) NOT NULL,           -- CONSOLIDATED, STANDALONE, etc.
    
    -- Balance Sheet Asset Columns
    CASH_AND_EQUIVALENTS NUMBER(20, 4),
    SHORT_TERM_INVESTMENTS NUMBER(20, 4),
    ACCOUNTS_RECEIVABLE NUMBER(20, 4),
    INVENTORY NUMBER(20, 4),
    PREPAID_EXPENSES NUMBER(20, 4),
    OTHER_CURRENT_ASSETS NUMBER(20, 4),
    TOTAL_CURRENT_ASSETS NUMBER(20, 4),
    
    LONG_TERM_INVESTMENTS NUMBER(20, 4),
    PROPERTY_PLANT_EQUIPMENT NUMBER(20, 4),
    ACCUMULATED_DEPRECIATION NUMBER(20, 4),
    INTANGIBLE_ASSETS NUMBER(20, 4),
    GOODWILL NUMBER(20, 4),
    OTHER_LONG_TERM_ASSETS NUMBER(20, 4),
    TOTAL_NON_CURRENT_ASSETS NUMBER(20, 4),
    
    TOTAL_ASSETS NUMBER(20, 4),
    
    -- Balance Sheet Liability Columns
    ACCOUNTS_PAYABLE NUMBER(20, 4),
    SHORT_TERM_DEBT NUMBER(20, 4),
    ACCRUED_LIABILITIES NUMBER(20, 4),
    DEFERRED_REVENUE NUMBER(20, 4),
    CURRENT_PORTION_LONG_TERM_DEBT NUMBER(20, 4),
    OTHER_CURRENT_LIABILITIES NUMBER(20, 4),
    TOTAL_CURRENT_LIABILITIES NUMBER(20, 4),
    
    LONG_TERM_DEBT NUMBER(20, 4),
    DEFERRED_TAX_LIABILITIES NUMBER(20, 4),
    PENSION_LIABILITIES NUMBER(20, 4),
    OTHER_LONG_TERM_LIABILITIES NUMBER(20, 4),
    TOTAL_NON_CURRENT_LIABILITIES NUMBER(20, 4),
    
    TOTAL_LIABILITIES NUMBER(20, 4),
    
    -- Balance Sheet Equity Columns
    COMMON_STOCK NUMBER(20, 4),
    PREFERRED_STOCK NUMBER(20, 4),
    ADDITIONAL_PAID_IN_CAPITAL NUMBER(20, 4),
    RETAINED_EARNINGS NUMBER(20, 4),
    TREASURY_STOCK NUMBER(20, 4),
    ACCUMULATED_OTHER_COMPREHENSIVE_INCOME NUMBER(20, 4),
    MINORITY_INTEREST NUMBER(20, 4),
    TOTAL_SHAREHOLDERS_EQUITY NUMBER(20, 4),
    
    TOTAL_LIABILITIES_AND_EQUITY NUMBER(20, 4),
    
    -- Metadata Columns
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY VARCHAR(100) DEFAULT CURRENT_USER(),
    DATA_HASH VARCHAR(64),  -- Hash of data columns for change detection
    
    -- Unique constraint on business grouping key
    CONSTRAINT UK_BUSINESS_KEY UNIQUE (
        PORTFOLIO_TICKER,
        REPORTING_FREQUENCY,
        REPORTING_CURRENCY,
        VALUE_DATE,
        PRELIMINARY,
        SOURCE,
        ACCT_BASIS,
        BALANCE_SHEET_TYPE
    )
);

SHOW TABLES;

SHOW COLUMNS;
-- Add comments for documentation
COMMENT ON TABLE ACTUAL_AA_BALANCE_SHEET IS 'Actual Balance Sheet data for financial reporting with daily delta tracking';
COMMENT ON COLUMN ACTUAL_AA_BALANCE_SHEET.PORTFOLIO_TICKER IS 'Unique identifier for the portfolio';
COMMENT ON COLUMN ACTUAL_AA_BALANCE_SHEET.REPORTING_FREQUENCY IS 'Frequency of reporting: DAILY, WEEKLY, MONTHLY, QUARTERLY, ANNUAL';
COMMENT ON COLUMN ACTUAL_AA_BALANCE_SHEET.REPORTING_CURRENCY IS 'Currency code for reporting values (ISO 4217)';
COMMENT ON COLUMN ACTUAL_AA_BALANCE_SHEET.VALUE_DATE IS 'The effective date of the balance sheet values';
COMMENT ON COLUMN ACTUAL_AA_BALANCE_SHEET.PRELIMINARY IS 'Flag indicating if data is preliminary (TRUE) or final (FALSE)';
COMMENT ON COLUMN ACTUAL_AA_BALANCE_SHEET.SOURCE IS 'Source system providing the data';
COMMENT ON COLUMN ACTUAL_AA_BALANCE_SHEET.ACCT_BASIS IS 'Accounting basis: GAAP, IFRS, STAT, etc.';
COMMENT ON COLUMN ACTUAL_AA_BALANCE_SHEET.BALANCE_SHEET_TYPE IS 'Type of balance sheet: CONSOLIDATED, STANDALONE, etc.';
COMMENT ON COLUMN ACTUAL_AA_BALANCE_SHEET.DATA_HASH IS 'SHA256 hash of data columns for efficient change detection';

SHOW TABLES LIKE 'ACTUAL_AA_BALANCE_SHEET';

