-- ============================================================================
-- Script: 04_daily_data_insert_procedure.sql
-- Purpose: Stored Procedure for Daily Data Insertion with MERGE
-- ============================================================================
USE ROLE SYSADMIN;
USE DATABASE FINANCE_DB;
USE SCHEMA BALANCE_SHEET;

-- ============================================================================
-- Create Staging Table for Incoming Data
-- ============================================================================
CREATE OR REPLACE TABLE INCOMING_DATA_STAGING (
    PORTFOLIO_TICKER VARCHAR(50),
    REPORTING_FREQUENCY VARCHAR(20),
    REPORTING_CURRENCY VARCHAR(10),
    VALUE_DATE DATE,
    PRELIMINARY BOOLEAN,
    SOURCE VARCHAR(100),
    ACCT_BASIS VARCHAR(20),
    BALANCE_SHEET_TYPE VARCHAR(50),
    CASH_AND_EQUIVALENTS NUMBER(20, 4),
    SHORT_TERM_INVESTMENTS NUMBER(20, 4),
    ACCOUNTS_RECEIVABLE NUMBER(20, 4),
    INVENTORY NUMBER(20, 4),
    PREPAID_EXPENSES NUMBER(20, 4),
    OTHER_CURRENT_ASSETS NUMBER(20, 4),
    TOTAL_CURRENT_ASSETS NUMBER(20, 4),
    LONG_TERM_INVESTMENTS NUMBER(20, 4),
    PROPERTY_PLANT_EQUIPMENT NUMBER(20, 4),
    ACCUMULATED_DEPRECIATION NUMBER(20, 4),
    INTANGIBLE_ASSETS NUMBER(20, 4),
    GOODWILL NUMBER(20, 4),
    OTHER_LONG_TERM_ASSETS NUMBER(20, 4),
    TOTAL_NON_CURRENT_ASSETS NUMBER(20, 4),
    TOTAL_ASSETS NUMBER(20, 4),
    ACCOUNTS_PAYABLE NUMBER(20, 4),
    SHORT_TERM_DEBT NUMBER(20, 4),
    ACCRUED_LIABILITIES NUMBER(20, 4),
    DEFERRED_REVENUE NUMBER(20, 4),
    CURRENT_PORTION_LONG_TERM_DEBT NUMBER(20, 4),
    OTHER_CURRENT_LIABILITIES NUMBER(20, 4),
    TOTAL_CURRENT_LIABILITIES NUMBER(20, 4),
    LONG_TERM_DEBT NUMBER(20, 4),
    DEFERRED_TAX_LIABILITIES NUMBER(20, 4),
    PENSION_LIABILITIES NUMBER(20, 4),
    OTHER_LONG_TERM_LIABILITIES NUMBER(20, 4),
    TOTAL_NON_CURRENT_LIABILITIES NUMBER(20, 4),
    TOTAL_LIABILITIES NUMBER(20, 4),
    COMMON_STOCK NUMBER(20, 4),
    PREFERRED_STOCK NUMBER(20, 4),
    ADDITIONAL_PAID_IN_CAPITAL NUMBER(20, 4),
    RETAINED_EARNINGS NUMBER(20, 4),
    TREASURY_STOCK NUMBER(20, 4),
    ACCUMULATED_OTHER_COMPREHENSIVE_INCOME NUMBER(20, 4),
    MINORITY_INTEREST NUMBER(20, 4),
    TOTAL_SHAREHOLDERS_EQUITY NUMBER(20, 4),
    TOTAL_LIABILITIES_AND_EQUITY NUMBER(20, 4),
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- Function to Generate Data Hash for Change Detection
-- ============================================================================
CREATE OR REPLACE FUNCTION GENERATE_DATA_HASH(
    CASH_EQ NUMBER, SHORT_INV NUMBER, ACCT_REC NUMBER, INV NUMBER,
    PREPAID NUMBER, OTHER_CA NUMBER, TOTAL_CA NUMBER,
    LONG_INV NUMBER, PPE NUMBER, ACCUM_DEP NUMBER, INTANG NUMBER,
    GDWL NUMBER, OTHER_LTA NUMBER, TOTAL_NCA NUMBER, TOTAL_A NUMBER,
    ACCT_PAY NUMBER, SHORT_DEBT NUMBER, ACCR_LIAB NUMBER, DEF_REV NUMBER,
    CURR_LTD NUMBER, OTHER_CL NUMBER, TOTAL_CL NUMBER,
    LONG_DEBT NUMBER, DEF_TAX NUMBER, PENSION NUMBER, OTHER_LTL NUMBER,
    TOTAL_NCL NUMBER, TOTAL_L NUMBER,
    COMMON NUMBER, PREF NUMBER, APIC NUMBER, RET_EARN NUMBER,
    TREASURY NUMBER, AOCI NUMBER, MINORITY NUMBER, TOTAL_EQ NUMBER,
    TOTAL_LE NUMBER
)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
    SHA2(
        COALESCE(TO_VARCHAR(CASH_EQ), '') || '|' ||
        COALESCE(TO_VARCHAR(SHORT_INV), '') || '|' ||
        COALESCE(TO_VARCHAR(ACCT_REC), '') || '|' ||
        COALESCE(TO_VARCHAR(INV), '') || '|' ||
        COALESCE(TO_VARCHAR(PREPAID), '') || '|' ||
        COALESCE(TO_VARCHAR(OTHER_CA), '') || '|' ||
        COALESCE(TO_VARCHAR(TOTAL_CA), '') || '|' ||
        COALESCE(TO_VARCHAR(LONG_INV), '') || '|' ||
        COALESCE(TO_VARCHAR(PPE), '') || '|' ||
        COALESCE(TO_VARCHAR(ACCUM_DEP), '') || '|' ||
        COALESCE(TO_VARCHAR(INTANG), '') || '|' ||
        COALESCE(TO_VARCHAR(GDWL), '') || '|' ||
        COALESCE(TO_VARCHAR(OTHER_LTA), '') || '|' ||
        COALESCE(TO_VARCHAR(TOTAL_NCA), '') || '|' ||
        COALESCE(TO_VARCHAR(TOTAL_A), '') || '|' ||
        COALESCE(TO_VARCHAR(ACCT_PAY), '') || '|' ||
        COALESCE(TO_VARCHAR(SHORT_DEBT), '') || '|' ||
        COALESCE(TO_VARCHAR(ACCR_LIAB), '') || '|' ||
        COALESCE(TO_VARCHAR(DEF_REV), '') || '|' ||
        COALESCE(TO_VARCHAR(CURR_LTD), '') || '|' ||
        COALESCE(TO_VARCHAR(OTHER_CL), '') || '|' ||
        COALESCE(TO_VARCHAR(TOTAL_CL), '') || '|' ||
        COALESCE(TO_VARCHAR(LONG_DEBT), '') || '|' ||
        COALESCE(TO_VARCHAR(DEF_TAX), '') || '|' ||
        COALESCE(TO_VARCHAR(PENSION), '') || '|' ||
        COALESCE(TO_VARCHAR(OTHER_LTL), '') || '|' ||
        COALESCE(TO_VARCHAR(TOTAL_NCL), '') || '|' ||
        COALESCE(TO_VARCHAR(TOTAL_L), '') || '|' ||
        COALESCE(TO_VARCHAR(COMMON), '') || '|' ||
        COALESCE(TO_VARCHAR(PREF), '') || '|' ||
        COALESCE(TO_VARCHAR(APIC), '') || '|' ||
        COALESCE(TO_VARCHAR(RET_EARN), '') || '|' ||
        COALESCE(TO_VARCHAR(TREASURY), '') || '|' ||
        COALESCE(TO_VARCHAR(AOCI), '') || '|' ||
        COALESCE(TO_VARCHAR(MINORITY), '') || '|' ||
        COALESCE(TO_VARCHAR(TOTAL_EQ), '') || '|' ||
        COALESCE(TO_VARCHAR(TOTAL_LE), '')
    , 256)
$$;

-- ============================================================================
-- Stored Procedure for Daily Data Insert/Update using MERGE
-- ============================================================================
CREATE OR REPLACE PROCEDURE DAILY_DATA_INSERT()
    RETURNS VARIANT
    LANGUAGE SQL
    EXECUTE AS CALLER
AS
$$
DECLARE
    v_inserted NUMBER := 0;
    v_updated NUMBER := 0;
    v_result VARIANT;
BEGIN
    -- MERGE statement: Insert new records, Update existing records based on business key
    MERGE INTO ACTUAL_AA_BALANCE_SHEET AS target
    USING (
        SELECT 
            PORTFOLIO_TICKER,
            REPORTING_FREQUENCY,
            REPORTING_CURRENCY,
            VALUE_DATE,
            PRELIMINARY,
            SOURCE,
            ACCT_BASIS,
            BALANCE_SHEET_TYPE,
            CASH_AND_EQUIVALENTS,
            SHORT_TERM_INVESTMENTS,
            ACCOUNTS_RECEIVABLE,
            INVENTORY,
            PREPAID_EXPENSES,
            OTHER_CURRENT_ASSETS,
            TOTAL_CURRENT_ASSETS,
            LONG_TERM_INVESTMENTS,
            PROPERTY_PLANT_EQUIPMENT,
            ACCUMULATED_DEPRECIATION,
            INTANGIBLE_ASSETS,
            GOODWILL,
            OTHER_LONG_TERM_ASSETS,
            TOTAL_NON_CURRENT_ASSETS,
            TOTAL_ASSETS,
            ACCOUNTS_PAYABLE,
            SHORT_TERM_DEBT,
            ACCRUED_LIABILITIES,
            DEFERRED_REVENUE,
            CURRENT_PORTION_LONG_TERM_DEBT,
            OTHER_CURRENT_LIABILITIES,
            TOTAL_CURRENT_LIABILITIES,
            LONG_TERM_DEBT,
            DEFERRED_TAX_LIABILITIES,
            PENSION_LIABILITIES,
            OTHER_LONG_TERM_LIABILITIES,
            TOTAL_NON_CURRENT_LIABILITIES,
            TOTAL_LIABILITIES,
            COMMON_STOCK,
            PREFERRED_STOCK,
            ADDITIONAL_PAID_IN_CAPITAL,
            RETAINED_EARNINGS,
            TREASURY_STOCK,
            ACCUMULATED_OTHER_COMPREHENSIVE_INCOME,
            MINORITY_INTEREST,
            TOTAL_SHAREHOLDERS_EQUITY,
            TOTAL_LIABILITIES_AND_EQUITY,
            GENERATE_DATA_HASH(
                CASH_AND_EQUIVALENTS, SHORT_TERM_INVESTMENTS, ACCOUNTS_RECEIVABLE, INVENTORY,
                PREPAID_EXPENSES, OTHER_CURRENT_ASSETS, TOTAL_CURRENT_ASSETS,
                LONG_TERM_INVESTMENTS, PROPERTY_PLANT_EQUIPMENT, ACCUMULATED_DEPRECIATION, INTANGIBLE_ASSETS,
                GOODWILL, OTHER_LONG_TERM_ASSETS, TOTAL_NON_CURRENT_ASSETS, TOTAL_ASSETS,
                ACCOUNTS_PAYABLE, SHORT_TERM_DEBT, ACCRUED_LIABILITIES, DEFERRED_REVENUE,
                CURRENT_PORTION_LONG_TERM_DEBT, OTHER_CURRENT_LIABILITIES, TOTAL_CURRENT_LIABILITIES,
                LONG_TERM_DEBT, DEFERRED_TAX_LIABILITIES, PENSION_LIABILITIES, OTHER_LONG_TERM_LIABILITIES,
                TOTAL_NON_CURRENT_LIABILITIES, TOTAL_LIABILITIES,
                COMMON_STOCK, PREFERRED_STOCK, ADDITIONAL_PAID_IN_CAPITAL, RETAINED_EARNINGS,
                TREASURY_STOCK, ACCUMULATED_OTHER_COMPREHENSIVE_INCOME, MINORITY_INTEREST, 
                TOTAL_SHAREHOLDERS_EQUITY, TOTAL_LIABILITIES_AND_EQUITY
            ) AS DATA_HASH
        FROM INCOMING_DATA_STAGING
    ) AS source
    ON (
        target.PORTFOLIO_TICKER = source.PORTFOLIO_TICKER AND
        target.REPORTING_FREQUENCY = source.REPORTING_FREQUENCY AND
        target.REPORTING_CURRENCY = source.REPORTING_CURRENCY AND
        target.VALUE_DATE = source.VALUE_DATE AND
        target.PRELIMINARY = source.PRELIMINARY AND
        target.SOURCE = source.SOURCE AND
        target.ACCT_BASIS = source.ACCT_BASIS AND
        target.BALANCE_SHEET_TYPE = source.BALANCE_SHEET_TYPE
    )
    WHEN MATCHED AND target.DATA_HASH != source.DATA_HASH THEN
        UPDATE SET
            target.CASH_AND_EQUIVALENTS = source.CASH_AND_EQUIVALENTS,
            target.SHORT_TERM_INVESTMENTS = source.SHORT_TERM_INVESTMENTS,
            target.ACCOUNTS_RECEIVABLE = source.ACCOUNTS_RECEIVABLE,
            target.INVENTORY = source.INVENTORY,
            target.PREPAID_EXPENSES = source.PREPAID_EXPENSES,
            target.OTHER_CURRENT_ASSETS = source.OTHER_CURRENT_ASSETS,
            target.TOTAL_CURRENT_ASSETS = source.TOTAL_CURRENT_ASSETS,
            target.LONG_TERM_INVESTMENTS = source.LONG_TERM_INVESTMENTS,
            target.PROPERTY_PLANT_EQUIPMENT = source.PROPERTY_PLANT_EQUIPMENT,
            target.ACCUMULATED_DEPRECIATION = source.ACCUMULATED_DEPRECIATION,
            target.INTANGIBLE_ASSETS = source.INTANGIBLE_ASSETS,
            target.GOODWILL = source.GOODWILL,
            target.OTHER_LONG_TERM_ASSETS = source.OTHER_LONG_TERM_ASSETS,
            target.TOTAL_NON_CURRENT_ASSETS = source.TOTAL_NON_CURRENT_ASSETS,
            target.TOTAL_ASSETS = source.TOTAL_ASSETS,
            target.ACCOUNTS_PAYABLE = source.ACCOUNTS_PAYABLE,
            target.SHORT_TERM_DEBT = source.SHORT_TERM_DEBT,
            target.ACCRUED_LIABILITIES = source.ACCRUED_LIABILITIES,
            target.DEFERRED_REVENUE = source.DEFERRED_REVENUE,
            target.CURRENT_PORTION_LONG_TERM_DEBT = source.CURRENT_PORTION_LONG_TERM_DEBT,
            target.OTHER_CURRENT_LIABILITIES = source.OTHER_CURRENT_LIABILITIES,
            target.TOTAL_CURRENT_LIABILITIES = source.TOTAL_CURRENT_LIABILITIES,
            target.LONG_TERM_DEBT = source.LONG_TERM_DEBT,
            target.DEFERRED_TAX_LIABILITIES = source.DEFERRED_TAX_LIABILITIES,
            target.PENSION_LIABILITIES = source.PENSION_LIABILITIES,
            target.OTHER_LONG_TERM_LIABILITIES = source.OTHER_LONG_TERM_LIABILITIES,
            target.TOTAL_NON_CURRENT_LIABILITIES = source.TOTAL_NON_CURRENT_LIABILITIES,
            target.TOTAL_LIABILITIES = source.TOTAL_LIABILITIES,
            target.COMMON_STOCK = source.COMMON_STOCK,
            target.PREFERRED_STOCK = source.PREFERRED_STOCK,
            target.ADDITIONAL_PAID_IN_CAPITAL = source.ADDITIONAL_PAID_IN_CAPITAL,
            target.RETAINED_EARNINGS = source.RETAINED_EARNINGS,
            target.TREASURY_STOCK = source.TREASURY_STOCK,
            target.ACCUMULATED_OTHER_COMPREHENSIVE_INCOME = source.ACCUMULATED_OTHER_COMPREHENSIVE_INCOME,
            target.MINORITY_INTEREST = source.MINORITY_INTEREST,
            target.TOTAL_SHAREHOLDERS_EQUITY = source.TOTAL_SHAREHOLDERS_EQUITY,
            target.TOTAL_LIABILITIES_AND_EQUITY = source.TOTAL_LIABILITIES_AND_EQUITY,
            target.UPDATED_TIMESTAMP = CURRENT_TIMESTAMP(),
            target.DATA_HASH = source.DATA_HASH
    WHEN NOT MATCHED THEN
        INSERT (
            PORTFOLIO_TICKER, REPORTING_FREQUENCY, REPORTING_CURRENCY, VALUE_DATE,
            PRELIMINARY, SOURCE, ACCT_BASIS, BALANCE_SHEET_TYPE,
            CASH_AND_EQUIVALENTS, SHORT_TERM_INVESTMENTS, ACCOUNTS_RECEIVABLE, INVENTORY,
            PREPAID_EXPENSES, OTHER_CURRENT_ASSETS, TOTAL_CURRENT_ASSETS,
            LONG_TERM_INVESTMENTS, PROPERTY_PLANT_EQUIPMENT, ACCUMULATED_DEPRECIATION,
            INTANGIBLE_ASSETS, GOODWILL, OTHER_LONG_TERM_ASSETS, TOTAL_NON_CURRENT_ASSETS,
            TOTAL_ASSETS, ACCOUNTS_PAYABLE, SHORT_TERM_DEBT, ACCRUED_LIABILITIES,
            DEFERRED_REVENUE, CURRENT_PORTION_LONG_TERM_DEBT, OTHER_CURRENT_LIABILITIES,
            TOTAL_CURRENT_LIABILITIES, LONG_TERM_DEBT, DEFERRED_TAX_LIABILITIES,
            PENSION_LIABILITIES, OTHER_LONG_TERM_LIABILITIES, TOTAL_NON_CURRENT_LIABILITIES,
            TOTAL_LIABILITIES, COMMON_STOCK, PREFERRED_STOCK, ADDITIONAL_PAID_IN_CAPITAL,
            RETAINED_EARNINGS, TREASURY_STOCK, ACCUMULATED_OTHER_COMPREHENSIVE_INCOME,
            MINORITY_INTEREST, TOTAL_SHAREHOLDERS_EQUITY, TOTAL_LIABILITIES_AND_EQUITY,
            CREATED_TIMESTAMP, UPDATED_TIMESTAMP, CREATED_BY, DATA_HASH
        )
        VALUES (
            source.PORTFOLIO_TICKER, source.REPORTING_FREQUENCY, source.REPORTING_CURRENCY, source.VALUE_DATE,
            source.PRELIMINARY, source.SOURCE, source.ACCT_BASIS, source.BALANCE_SHEET_TYPE,
            source.CASH_AND_EQUIVALENTS, source.SHORT_TERM_INVESTMENTS, source.ACCOUNTS_RECEIVABLE, source.INVENTORY,
            source.PREPAID_EXPENSES, source.OTHER_CURRENT_ASSETS, source.TOTAL_CURRENT_ASSETS,
            source.LONG_TERM_INVESTMENTS, source.PROPERTY_PLANT_EQUIPMENT, source.ACCUMULATED_DEPRECIATION,
            source.INTANGIBLE_ASSETS, source.GOODWILL, source.OTHER_LONG_TERM_ASSETS, source.TOTAL_NON_CURRENT_ASSETS,
            source.TOTAL_ASSETS, source.ACCOUNTS_PAYABLE, source.SHORT_TERM_DEBT, source.ACCRUED_LIABILITIES,
            source.DEFERRED_REVENUE, source.CURRENT_PORTION_LONG_TERM_DEBT, source.OTHER_CURRENT_LIABILITIES,
            source.TOTAL_CURRENT_LIABILITIES, source.LONG_TERM_DEBT, source.DEFERRED_TAX_LIABILITIES,
            source.PENSION_LIABILITIES, source.OTHER_LONG_TERM_LIABILITIES, source.TOTAL_NON_CURRENT_LIABILITIES,
            source.TOTAL_LIABILITIES, source.COMMON_STOCK, source.PREFERRED_STOCK, source.ADDITIONAL_PAID_IN_CAPITAL,
            source.RETAINED_EARNINGS, source.TREASURY_STOCK, source.ACCUMULATED_OTHER_COMPREHENSIVE_INCOME,
            source.MINORITY_INTEREST, source.TOTAL_SHAREHOLDERS_EQUITY, source.TOTAL_LIABILITIES_AND_EQUITY,
            CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), CURRENT_USER(), source.DATA_HASH
        );

    -- Truncate staging table after successful merge
    TRUNCATE TABLE INCOMING_DATA_STAGING;
    
    -- Return summary
    v_result := OBJECT_CONSTRUCT(
        'status', 'SUCCESS',
        'message', 'Daily data insert completed',
        'timestamp', CURRENT_TIMESTAMP()
    );
    
    RETURN v_result;
END;
$$;

COMMENT ON PROCEDURE DAILY_DATA_INSERT() IS 
'Merges incoming data into ACTUAL_AA_BALANCE_SHEET based on business grouping key';

